"""Add success_stories table

Revision ID: 2693525ae38e
Revises: 1a2b3c4d5e6f
Create Date: 2026-07-12 23:47:17.974062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2693525ae38e'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('success_stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_mr', sa.String(), nullable=False),
    sa.Column('loss_en', sa.String(), nullable=False),
    sa.Column('loss_mr', sa.String(), nullable=False),
    sa.Column('feedback_en', sa.String(), nullable=False),
    sa.Column('feedback_mr', sa.String(), nullable=False),
    sa.Column('before_image', sa.String(), nullable=False),
    sa.Column('after_image', sa.String(), nullable=False),
    sa.Column('before_weight', sa.String(), nullable=True),
    sa.Column('after_weight', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('success_stories')
    # ### end Alembic commands ###
