"""Add client fields and progress model

Revision ID: f6040af5f14a
Revises: d948fca1b2dc
Create Date: 2026-07-15 14:25:15.102093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6040af5f14a'
down_revision: Union[str, Sequence[str], None] = 'd948fca1b2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_logs_date'), 'progress_logs', ['date'], unique=False)
    op.create_index(op.f('ix_progress_logs_id'), 'progress_logs', ['id'], unique=False)
    op.create_index(op.f('ix_progress_logs_user_id'), 'progress_logs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('mobile_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('target_weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('streak', sa.Integer(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'streak')
    op.drop_column('users', 'target_weight')
    op.drop_column('users', 'height')
    op.drop_column('users', 'role')
    op.drop_column('users', 'mobile_number')
    op.drop_index(op.f('ix_progress_logs_user_id'), table_name='progress_logs')
    op.drop_index(op.f('ix_progress_logs_id'), table_name='progress_logs')
    op.drop_index(op.f('ix_progress_logs_date'), table_name='progress_logs')
    op.drop_table('progress_logs')
    # ### end Alembic commands ###
